---
title: ""
subtitle: "PHP2550 Project 3: A simulation analysis"
author: "Yanwei (Iris) Tong"
date: "2024-11-12"
output: 
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    #number_sections: true
link-citations: yes
header-includes:
  - "\\usepackage{xcolor}"
abstract: |
  **Purpose:** 
  
  **Methods**:     
  
  **Results and conclusion**: 
  

geometry: margin=1in
fontsize: 10.5pt
csl: 0-american-statistical-association.csl
bibliography: 0-references.bib
---



```{r setup, include=FALSE}
# to prevent scientific notation
options(scipen=999)

# Set up knit environment
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      error = FALSE)

# Load necessary packages
library(tidyverse)
library(kableExtra)
library(knitr)
library(ggplot2)
library(gridExtra)
library(grid)
library(naniar)
library(gtsummary)
library(gt)
library(patchwork)
library(knitcitations)
library(mice)
library(glmnet)
library(pROC)
library(MASS)
library(leaps)
library(RColorBrewer) 
library(cowplot)
```


# \textcolor{orange}{INTRODUCTION}




# \textcolor{orange}{SIMULATION DESIGN}

# \textcolor{orange}{ESTIMAND}

# \textcolor{orange}{PERFORMANCE EVALUATION}



# \textcolor{orange}{CONCLUSION}


# \textcolor{orange}{LIMITATIONS}


# Data, and Code Availability

 Replication scripts are available at <https://github.com/YanweiTong-Iris/PHP2550-Fall24/tree/main/Project2>.

# Reference
<div id="refs"></div>


\pagebreak

# Code Appendix

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```
